on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Show release output created
        run: echo "Release created ${{ steps.release.outputs.releases_created}}"
      - uses: actions/checkout@v4
      - name: tag major and minor versions
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: |
          echo "Parsing paths_released..."
          paths_released=$(echo '${{ steps.release.outputs.paths_released }}' | jq -r '.[]')
          for path in $paths_released; do
            echo "Processing path: $path"

            # GitHub Actions environment variables allow dynamic access to outputs
            major_var="${path}--major"
            minor_var="${path}--minor"

            # Access the dynamic outputs via environment variable substitution
            major="${{ steps.release.outputs[major_var] }}"
            minor="${{ steps.release.outputs[minor_var] }}"

            echo "Major version for $path: $major"
            echo "Minor version for $path: $minor"

            # Git config
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/MaximilianGewers/mono-repo-test.git"

            # Delete tags if they exist
            git tag -d "${path}@v${major}" || true
            git tag -d "${path}@v${major}.${minor}" || true
            git push origin ":${path}@v${major}" || true
            git push origin ":${path}@v${major}.${minor}" || true

            # Create and push new tags
            git tag -a "${path}@v${major}" -m "Release ${path}@v${major}"
            git tag -a "${path}@v${major}.${minor}" -m "Release ${path}@v${major}.${minor}"
            git push origin "${path}@v${major}"
            git push origin "${path}@v${major}.${minor}"
          done
